Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-18.04"
  c.vm.hostname = "test-vagrant-1804.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/home/tvisher/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-temp_bundler_1804-test-vagrant-1804-87d461ba-87dd-492f-974b-64a68c6de45d"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
