Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu/bionic64"
  c.vm.hostname = "test-ubuntu-1404.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-temp_bundler_1804-test-ubuntu-1404-2083891a-cd4c-49a7-8716-bbedbe95b8ab"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
